version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gs-frontend
    ports:
      - "8086:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped

networks:
  default:
    name: gs-network
    driver: bridge