version: '3.8'

networks:
  gs-network:
    driver: bridge

  api-front-network:
    external: true

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gs-frontend
    ports:
      - "8086:4200"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    networks:
      - gs-network
      - api-front-network